import React from 'react';
import { useState } from 'react';
import { FormField, Loader } from '../components';

const RenderCards = ({ data, title }) => {
  if (data?.length > 0) {
    return data.map(post => <Card key={post._id} {...post} />);
  }
  return (
    <h2 className='uppercase font-bold mt-5 text-xl text-[#6449ff]'>{title}</h2>
  );
};

function Home() {
  const [loading, setLoading] = useState(false);
  const [searchText, setSearchText] = useState('');
  return (
    <section className='max-w-7xl mx-auto'>
      <div>
        <h1 className='font-extrabold text-[#222328] text-[32px]'>
          The Community Showcase
        </h1>
        <p className='mt-2  text-[16px] text-[#666e75] max-w[500px]'>
          Browse through a collection of imaginative and visually stunning
          images generated by DALL-E AI
        </p>
      </div>
      <div className='mt-16'>
        <FormField />
      </div>
      <div>
        {loading ? (
          <div className='flex items-center justify-center'>
            <Loader />
          </div>
        ) : (
          <>
            {searchText && (
              <h2 className='font-medium text-[#666e75] text-xl mb-3'>
                Showing results for{' '}
                <span className='text-[#222328]'>{searchText}</span>
              </h2>
            )}
            <div className='grid lg:grid-cols-4 sm:grid-cols-3 xs:grid-cols-2 grid-cols-1 gap-3'>
              {searchText ? (
                <RenderCards data={[]} title={'Searched Results'} />
              ) : (
                <RenderCards data={[]} title={'No Post Found!'} />
              )}
            </div>
          </>
        )}
      </div>
    </section>
  );
}

export default Home;
